services:
  telegraf:
    image: telegraf
    container_name: telegraf
    restart: always
    user: telegraf
    volumes:
      - ./container-resources/telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro  
    depends_on:
      - influxdb
    ports:
      - '8126:8126'
    networks: 
      - dev-fsof
  influxdb:
    image: influxdb:1.8-alpine
    container_name: influxdb
    restart: always
    environment:
      - INFLUXDB_DB=influx
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin
      - INFLUXDB_REPORTING_DISABLED=true
    ports:
      - '8086:8086'
    volumes:
      - ./container-resourcers/influx/influxdb_data:/var/lib/influxdb
    networks: 
      - dev-fsof
  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    restart: always
    depends_on:
      - influxdb
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    ports:
      - '3000:3000'
    volumes:
      - ./container-resourcers/grafana/grafana_data:/var/lib/grafana  
    networks: 
      - dev-fsof

networks:
  dev-fsof:
    driver: bridge