services:
  # frontend:
  #   build: ./frontend
  #   ports:
  #     - "3000:3000"
  # backend:
  #   depends_on:
  #     - db
  #     - broker
  #   volumes:
  #     - ./container-resources/backend/tomcat/logging.properties:/usr/local/tomcat/conf/logging.properties
  #     - ./container-resources/backend/jrebel/jrebel.jar:/jrebel.jar 
  #     - ./container-resources/backend/jrebel/lib/libjrebel64.so:/lib/libjrebel64.so
  #     - ./backend/target/backend.war:/usr/local/tomcat/webapps/ROOT.war
  #   build: 
  #     dockerfile: ./backend/Dockerfile.development
  #   environment:
  #     JAVA_OPTS: "-agentpath:/lib/libjrebel64.so -Drebel.remoting_plugin=true -Drebel.log.file=/jrebel.log -Dsupplements.host=supplements"
  #   ports:
  #     - "8888:8080"
  mqtt5:
    image: eclipse-mosquitto
    container_name: mqtt5
    ports:
      - "1883:1883" #default mqtt port
      - "9001:9001" #default mqtt port for websockets
    volumes:
      - ./container-resources/mqtt/config:/mosquitto/config:rw
      - ./container-resources/mqtt/data:/mosquitto/data:rw
      - ./container-resources/mqtt/log:/mosquitto/log:rw
    restart: unless-stopped
    networks: 
      - dev-fsof
  # mqtt-kafka-bridge:
  #   build: ./mqtt-kafka-bridge
  #   restart: unless-stopped
  #   depends_on:
  #     - broker
  broker:
    image: confluentinc/confluent-local:7.4.1
    hostname: broker
    container_name: broker
    ports:
      - "8082:8082"
      - "9092:9092"
      - "9101:9101"
    environment:
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://broker:29092,PLAINTEXT_HOST://localhost:9092'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@broker:29093'
      KAFKA_LISTENERS: 'PLAINTEXT://broker:29092,CONTROLLER://broker:29093,PLAINTEXT_HOST://0.0.0.0:9092'

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    ports:
      - 9999:8080
    environment:
      DYNAMIC_CONFIG_ENABLED: true
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: broker:29092
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest 
    environment:
      - "ACCEPT_EULA=Y"
      - "MSSQL_SA_PASSWORD=1111ubersakYTA(-_!)33333" #dont even think this is prod
      - "MSSQL_PID=Express"
      - "MSSQL_AGENT_ENABLED=false"
    volumes:
      - ./container-resources/database/:/scripts/
    entrypoint: [ "/bin/bash", "/scripts/entrypoint.sh" ]
    ports: 
      - "1433:1433"

networks:
  dev-fsof:
    driver: bridge