apiVersion: v1
kind: ConfigMap
metadata:
  name: telegraf-config
data:
  telegraf.conf: |
    [[outputs.influxdb]]
      urls = ["{{ .Values.telegraf.influxdb.url }}"]
      database = "{{ .Values.telegraf.influxdb.database }}"

    [[inputs.mqtt_consumer]]
      servers = ["{{ .Values.telegraf.mqtt.broker }}"]
      topics = {{ toJson .Values.telegraf.mqtt.topics }}
      data_format = "json"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: telegraf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: telegraf
  template:
    metadata:
      labels:
        app: telegraf
    spec:
      containers:
        - name: telegraf
          image: {{ .Values.telegraf.image }}
          volumeMounts:
            - name: telegraf-config-volume
              mountPath: /etc/telegraf/
          args: ["--config", "/etc/telegraf/telegraf.conf"]
      volumes:
        - name: telegraf-config-volume
          configMap:
            name: telegraf-config
